package net.blockserver.network.minecraft;

public enum PacketID {
	CURRENT_PROTOCOL (14),
    PING ((byte) 0x00),
    PONG (0x03),

	 CLIENT_CONNECT (0x09),
	 SERVER_HANDSHAKE (0x10),
	
	 CLIENT_HANDSHAKE (0x13),
	
	 SERVER_FULL (0x14),
	 DISCONNECT (0x15),
	
	 BANNED (0x17),
	
	 LOGIN (0x82),
	 LOGIN_STATUS (0x83),
	 READY (0x84),
	 MESSAGE (0x85),
	 SET_TIME (0x86),
	 START_GAME (0x87),
	 ADD_MOB (0x88),
	 ADD_PLAYER (0x89),
	 REMOVE_PLAYER (0x8a),
	
	 ADD_ENTITY (0x8c),
	 REMOVE_ENTITY (0x8d),
	 ADD_ITEM_ENTITY (0x8e),
	 TAKE_ITEM_ENTITY (0x8f),
	 MOVE_ENTITY (0x90),
	
	 MOVE_ENTITY_POSROT (0x93),
	 ROTATE_HEAD (0x94),
	 MOVE_PLAYER (0x95),
	 PLACE_BLOCK (0x96),
	 REMOVE_BLOCK (0x97),
	 UPDATE_BLOCK (0x98),
	 ADD_PAINTING (0x99),
	 EXPLODE (0x9a),
	 LEVEL_EVENT (0x9b),
	 TILE_EVENT (0x9c),
	 ENTITY_EVENT (0x9d),
	 REQUEST_CHUNK (0x9e),
	 CHUNK_DATA (0x9f),
	 PLAYER_EQUIPMENT (0xa0),
	 PLAYER_ARMOR_EQUIPMENT (0xa1),
	 INTERACT (0xa2),
	 USE_ITEM (0xa3),
	 PLAYER_ACTION (0xa4),
	
	 HURT_ARMOR (0xa6),
	 SET_ENTITY_DATA (0xa7),
	 SET_ENTITY_MOTION (0xa8),
	 SET_ENTITY_LINK (0xa9),
	 SET_HEALTH (0xaa),
	 SET_SPAWN_PODSITION (0xab),
	 ANIMATE (0xac),
	 RESPAWN (0xad),
	 SEND_INVENTORY (0xae),
	 DROP_ITEM (0xaf),
	 CONTAINER_OPEN (0xb0),
	 CONTAINER_CLOSE (0xb1),
	 CONTAINER_SET_SLOT (0xb2),
	 CONTAINER_SET_DATA (0xb3),
	 CONTAINER_SET_CONTENT (0xb4),
	 CONTAINER_ACK (0xb5),
	 CHAT (0xb6),
	 ADVENTURE_SETTINGS(0xb7),
	 ENTITY_DATA (0xb8),
	 PLAYER_INPUT (0xb9);
	
	private int value;
	
	private PacketID(int value){
		this.value = value;
	}
	
	public int getValue(){
		return value;
	}

}
